export const SUPPORTED_GPUS = [
  {
    model: "NVIDIA GeForce GTX 950",
    transcoding: true,
    ethashMining: false,
    notes: "Benchmarks",
    noteLink:
      "https://forum.livepeer.org/t/gtx-950-quadro-p400-benchmarks/1497",
  },
  {
    model: "NVIDIA GeForce GTX 1060",
    transcoding: true,
    ethashMining: true,
    notes: "",
    noteLink: "",
  },
  {
    model: "NVIDIA GeForce GTX 1070",
    transcoding: true,
    ethashMining: false,
    notes: "",
    noteLink: "",
  },
  {
    model: "NVIDIA GeForce GTX 1070 Ti",
    transcoding: true,
    ethashMining: true,
    notes: "",
    noteLink: "",
  },
  {
    model: "NVIDIA GeForce GTX 1080",
    transcoding: true,
    ethashMining: false,
    notes: "",
    noteLink: "",
  },
  {
    model: "NVIDIA GeForce GTX 1080 Ti",
    transcoding: true,
    ethashMining: false,
    notes: "",
    noteLink: "",
  },
  {
    model: "NVIDIA Tesla T4",
    transcoding: true,
    ethashMining: false,
    notes: "",
    noteLink: "",
  },
  {
    model: "NVIDIA GeForce GTX 1660 Ti",
    transcoding: true,
    ethashMining: false,
    notes: "",
    noteLink: "",
  },
  {
    model: "NVIDIA GeForce GTX 1660 SUPER",
    transcoding: true,
    ethashMining: false,
    notes: "",
    noteLink: "",
  },
  {
    model: "NVIDIA GeForce GTX 2080 Ti",
    transcoding: true,
    ethashMining: true,
    notes: "",
    noteLink: "",
  },
  {
    model: "NVIDIA GeForce RTX 3080",
    transcoding: true,
    ethashMining: true,
    notes: "Benchmarks",
    noteLink:
      "https://forum.livepeer.org/t/dual-ethash-mining-transcoding-w-rtx-3080-10g-cuda-mps/1161",
  },
  {
    model: "NVIDIA GeForce GTX 3090",
    transcoding: true,
    ethashMining: true,
    notes: "",
    noteLink: "",
  },
  {
    model: "NVIDIA Titan V",
    transcoding: true,
    ethashMining: true,
    notes: "",
    noteLink: "",
  },
  {
    model: "NVIDIA Quadro P400",
    transcoding: true,
    ethashMining: false,
    notes: "Benchmarks",
    noteLink:
      "https://forum.livepeer.org/t/gtx-950-quadro-p400-benchmarks/1497",
  },
  {
    model: "NVIDIA Quadro T600",
    transcoding: true,
    ethashMining: false,
    notes: "Benchmarks",
    noteLink: "https://forum.livepeer.org/t/nvidia-quadro-t600-benchmark/1650",
  },
  {
    model: "NVIDIA GeForce RTX 3060",
    transcoding: true,
    ethashMining: false,
    notes: "",
    noteLink: "",
  },
];
